version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=test.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
